<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>narmast</name>
   <tag></tag>
   <elementGuidId>4739c21a-bd26-4986-8218-520d79d9f458</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-laundry/div/div[2]/div/div[contains(@class,'detail-wrapper')]/div[5]/div[2]/div/app-radio/div[1]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
