<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>renovering</name>
   <tag></tag>
   <elementGuidId>c4b4de47-71e0-4a47-87c8-ad867dc42d54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-laundry/div/div[2]/div/div[contains(@class,'detail-wrapper')]/div[3]/div[2]/div/app-radio/div[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
