<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vattentat</name>
   <tag></tag>
   <elementGuidId>902671a5-0027-4042-bb01-8cdb5a5ef66d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-laundry/div/div[2]/div/div[contains(@class,'detail-wrapper')]/div[4]/div[2]/div/app-radio/div[1]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
