<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>golvytan</name>
   <tag></tag>
   <elementGuidId>6777bcb4-2744-46c9-a110-22ab96733ff5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-water-heater/div/div[2]/div/div[contains(@class,'detail-wrapper')]/div[3]/div[2]/div/app-radio/div[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
