<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bygg</name>
   <tag></tag>
   <elementGuidId>9da72b47-554b-43e8-9243-b8d474dbbd50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-kitchen/div/div[2]/div/div[contains(@class,'detail-wrapper')]/div[1]/div[2]/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
