<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>disbankksapet</name>
   <tag></tag>
   <elementGuidId>5b4cab1b-fbef-4e3b-be45-e54220ebdb19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-kitchen/div/div[2]/div/div[contains(@class,'detail-wrapper')]/div[7]/div[2]/div/app-radio/div[1]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
