<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Vatten</name>
   <tag></tag>
   <elementGuidId>e22a066b-faad-424f-a826-de33fb608a69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-kitchen/div/div[2]/div/div[contains(@class,'detail-wrapper')]/div[5]/div[2]/div/app-radio/div[1]/i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
