<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>E-post</name>
   <tag></tag>
   <elementGuidId>4b4ac465-1bb3-47b8-8064-ef463dca8761</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-personal-info/div/div[2]/div/div[contains(@class,'detail-wrapper')]/div[8]/div[2]/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
