<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Utdelningsaddress</name>
   <tag></tag>
   <elementGuidId>d8b1d4a8-f944-41ca-aa15-49b2ed0d47f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-personal-info/div/div[2]/div/div[contains(@class,'detail-wrapper')]/div[4]/div[2]/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
