<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Villans</name>
   <tag></tag>
   <elementGuidId>e640cd9d-f052-439d-b6b7-3e69ab4cdd91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-personal-info/div/div[2]/div/div[contains(@class,'detail-wrapper')]/div[9]/div[2]/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
