<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>branslackare</name>
   <tag></tag>
   <elementGuidId>9ed1e564-a33d-4beb-9e12-66f7634a79c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-firesafety/div/div[2]/div/div[contains(@class,'detail-wrapper')]/div[2]/div[2]/div/app-radio/div[1]/i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
