<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>forvaras</name>
   <tag></tag>
   <elementGuidId>424769e8-4ce8-4274-ac2f-c01d06e27964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-firesafety/div/div[2]/div/div[contains(@class,'detail-wrapper')]/div[6]/div[2]/div/app-radio/div[1]/i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
