<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>duschstang</name>
   <tag></tag>
   <elementGuidId>810059f0-9026-44c0-a826-1abb211694b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-bathroom/div/div[3]/div/div[contains(@class,'detail-wrapper')]/div[4]/div[2]/div/app-radio/div[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
