<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>golvytan</name>
   <tag></tag>
   <elementGuidId>8cf3b815-a233-415b-97c3-60f4cdbcc82d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-bathroom/div/div[3]/div/div[contains(@class,'detail-wrapper')]/div[5]/div[2]/div/app-radio/div[1]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
