<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>renovering</name>
   <tag></tag>
   <elementGuidId>5aa2775d-e073-4068-891a-5890b2e96865</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-bathroom/div/div[3]/div/div[contains(@class,'detail-wrapper')]/div[3]/div[2]/div/app-radio/div[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
